sudo: false
language: ruby
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # Required to avoid TLS errors
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - ASSET_HOST_URL="https://github.githubassets.com"

script:
  - set -e # halt script on error
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site
